name: SAST CodeQL Scan
on: [push, pull_request]

jobs:
  codeql:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: java

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Run CodeQL analysis
        id: analyze
        uses: github/codeql-action/analyze@v3
        with:
          output: sarif-results

      - name: Upload SARIF results as artifact
        uses: actions/upload-artifact@v4
        with:
          name: codeql-sarif
          path: sarif-results/*.sarif
